// A Mixed Bag - Interactive Disc Golf Story Data
const STORY_DATA = {
  "start": {
    "text": "A MIXED BAG\n\nAs the early morning sunlight filters through the blinds, you stretch and yawn, feeling a surge of excitement for the day ahead. You hope today is a perfect day for disc golf. You roll out of bed, grab your phone and open the weather app.\n\n\"Please be nice outside today,\" you mutter, tapping the screen with anticipation.\n\nClear skies, a gentle breeze, and a comfortable 70 degrees. Perfect. You grin, feeling the adrenaline of the game already starting to pump through your veins. After a quick shower and breakfast, you gather your gear.",
    "choices": [{"text": "Leave the house", "goto": "Leave the house"}]
  },
  "Leave the house": {
    "text": "Your disc golf bag sits by the front door. You grab it and get ready to head out. After counting your discs to ensure everything is in order, you pause to admire your collection. Each disc has a story, a memory of a great shot or a challenging course. With the weather confirmed and your discs accounted for, you feel ready to take on the course.\n\nToday's destination is Smokey Pines Disc Golf Course, a local favorite known for its challenging layout and beautiful scenery. The park features a mix of wooded areas and open fields, demanding a variety of shots and strategies.\n\nPulling into the parking lot, you take a moment to take in the surroundings. The parking area is already bustling with other disc golfers, chatting excitedly and preparing their gear. You spot a few familiar faces and exchange friendly nods and waves. You grab your disc golf bag and a water bottle then head towards the first tee.",
    "choices": [{"text": "Step up to the 1st tee", "goto": "Step up to the 1st tee"}]
  },
  "Step up to the 1st tee": {
    "text": "The first hole at Smokey Pines is a classic starter, a 300-foot par 3 that requires a precise throw to navigate through a narrow gap between two large oak trees. You stand at the tee pad, surveying the landscape. The fairway stretches out in front of you, flanked by dense woods on either side.\n\nYou reach into your bag and pull out a few options, considering each one carefully. You have an ESP Nuke, a reliable distance driver. It feels like a solid choice in the headwind. The C-Line MD3, a versatile midrange, offers control but might lack the distance needed for this hole, and your trusty Champion Teebird. It has the perfect balance of stability and distance, ideal for threading the gap and getting close to the basket. Which disc do you choose?",
    "choices": [
      {"text": "Nuke", "goto": "Nuke"},
      {"text": "MD3", "goto": "MD3"},
      {"text": "TeeBird", "goto": "TeeBird"}
    ]
  },
  "Nuke": {
    "text": "The goal is to unleash the Nuke down the center of the fairway, letting it carry as far as possible. With a powerful wind-up, you release your disc, feeling the force of the throw. The Nuke shoots forward like a rocket, slicing through the air with incredible speed. It turns slightly to the right, riding the downhill slope and gaining distance with every second. The disc's glide is exceptional, allowing it to cover an impressive amount of distance before fading back to the left.\n\nUnfortunately, you've overthrown the basket and landed in the woods. Your approach is tough and you leave yourself a long putt to save par. You take your time, line up your putt carefully, and go through your routine. The putt hits the top band hard and falls down in front of the basket. You'll need to make up this bogey later.",
    "choices": [{"text": "Move On", "goto": "Move On"}]
  },
  "MD3": {
    "text": "The MD3 flies straight, its stability keeping it on a tight line through the fairway. The disc glides effortlessly, avoiding the trees and staying on its intended path. As it approaches the cluster of oaks near the basket, the MD3 begins a subtle fade, heading towards the basket, but lands well short.\n\nWith your putter in hand, you line up your shot, focusing on the chains. The distance requires a bit of extra concentration to ensure the disc will hold its line. You steady yourself, take a deep breath, and release the putter.\n\nYour putt hits the chains dead center and drops into the basket with a satisfying sound. You just made a 45ft putt for an amazing birdie. What a great way to start your round.",
    "choices": [{"text": "On to the next hole", "goto": "On to the next hole"}]
  },
  "TeeBird": {
    "text": "After a moment's contemplation, you decide on the Teebird. Stepping onto the tee pad, you take a deep breath, feeling the weight of the disc in your hand. Feet planted firmly, you visualize your throw, and the disc soaring through the air.\n\nWith a smooth motion, you launch the Teebird, watching as it flies straight and true, slicing through the gap and landing gracefully on the fairway. A satisfied smile spreads across your face. The game was on, and it was going to be a great day of disc golf.\n\nThe Teebird's perfect flight sets a positive tone for the round. Walking down the fairway, you see your disc, and it is clear you are well within putting range. With a gentle flick of the wrist, you send your putter sailing into the basket with a satisfying crash into the chains.",
    "choices": [{"text": "Head to the next hole", "goto": "Head to the next hole"}]
  },
  "Head to the next hole": {
    "text": "As the game progresses, each hole brings new challenges and choices, but your consistency and confidence remain. With each successful throw, you feel more in tune with the course and the discs. It's one of those rare days when everything seems to click, and the joy of the game is in full bloom.\n\nA few holes later, you are presented with the first real challenge of the day, a 450-foot par 4. It requires a strong drive followed by a precise approach. You take a moment to consider your discs. The options are the reliable Champion Beast, or the faster Star Wraith. Which disc do you choose?",
    "choices": [
      {"text": "Beast", "goto": "Beast"},
      {"text": "Wraith", "goto": "Wraith"}
    ]
  },
  "Beast": {
    "text": "You step up to the tee pad, planting your feet firmly. The wide-open fairway stretches out invitingly, with a slight tailwind promising to add a bit more distance to the throw. You visualize the perfect flight path: a powerful, straight drive that will ride the wind and fade off to the left, setting up a favorable position for the second shot.\n\nYou take a few practice swings, feeling the weight and balance of the Beast. The moment feels right. With fluid motion, you wind up and release the disc, watching as it soars into the sky. The Beast shoots forward with impressive speed, cutting through the air with a audible whoosh.\n\nThe tailwind catches the disc, giving it an extra boost. It flies straight and true, its high-speed turn keeping it on a steady course. As it reaches the apex of its flight, the Beast begins its gentle fade to the left, gliding gracefully down the fairway and lands just a few feet from the pin.",
    "choices": [{"text": "Walk to your disc", "goto": "Walk to your disc"}]
  },
  "Wraith": {
    "text": "Looking at the hole layout, you decide on the Star Wraith. The added distance will be beneficial, and the stability will help navigate the slight headwind. Planting your feet, you concentrate on the target, draw back, and unleash a powerful throw. The Wraith flies with a lot of speed and distance, flying through the air and landing in a favorable position on the fairway.\n\nThe second shot will need to be near perfect to avoid the surrounding trees and get close to the basket. With a nice throw, your disc soars through the gap, landing softly just outside circle 1. The putt is a bit tricky, with a slight uphill lie. Taking a deep breath, you focus, aim, and miss the putt, then tap in a par. It wasn't a birdie, but it was a solid performance on a challenging hole.",
    "choices": [{"text": "Walk to the next hole.", "goto": "Walk to the next hole."}]
  },
  "Walk to your disc": {
    "text": "The drive with the Champion Beast had set the stage perfectly, and the approach is executed flawlessly. A simple tap-in for birdie awaits.\n\nAs you approach the tee pad for the next hole, a sense of anticipation fills the air. This hole, a 475-foot par 4, is known for its wide-open fairway that begs for a powerful drive. The basket is positioned at the edge of a slight downhill slope, with a few strategically placed trees near the end to challenge the approach. You try to decide between 2 of your drivers, the Champion Boss and the Star Katana. Which disc do you choose?",
    "choices": [
      {"text": "Boss", "goto": "Boss"},
      {"text": "Katana", "goto": "Katana"}
    ]
  },
  "Boss": {
    "text": "You take a moment to think about your shot. The plan is to send the Boss soaring straight down the fairway, letting its stability handle the slight turn and fade. You wind up and release the Boss with all the power and control you can muster.\n\nThe Boss flies like a missile, cutting through the air with remarkable speed. It holds a straight line for most of its flight, then begins a subtle right turn, perfectly navigating the dogleg. As it reaches its maximum distance, the Boss fades to the left, landing far down the fairway and setting up a great position for the second shot.",
    "choices": [{"text": "Head toward your disc", "goto": "Head toward your disc"}]
  },
  "Katana": {
    "text": "You rummage through your bag and pull out the Star Katana, feeling its sleek, grippy plastic. The disc has a beautiful design that makes the disc look awesome. Standing at the tee pad, you think a powerful throw that turns slightly right, threading through the narrow gap will be the best option.\n\nYou settle into your throwing stance. The tall pines flank the fairway, their presence adding a hint of pressure to the throw. After a slow, controlled x-step, you release the Katana, feeling the familiar snap of the disc leaving your hand.\n\nThe Katana soars through the air, its flight path exactly as envisioned. It turns a bit to the right, navigating the narrow gap perfectly. As it continues down the fairway, the disc begins to fade back left, landing in the open area beyond the trees. You can't help but smile, the Katana had done its job beautifully.",
    "choices": [{"text": "Finish your round", "goto": "Finish your round"}]
  },
  "Walk to the next hole.": {
    "text": "You approach the tee pad for the next hole, a notoriously tricky part of the course known as \"The Gauntlet.\" It is a 375-foot par 3, with a narrow, winding fairway heavily wooded on both sides. The hole is extremely difficult, with little room for error. A slight deviation could mean hitting a tree and potentially adding a few extra strokes to your score.\n\nStanding at the tee pad, you carefully assess the situation. Two discs stand out as potential choices: the Star TL3 and the Champion Sidewinder. Both had their merits, but selecting the right one could make or break this round. Which disc do you choose?",
    "choices": [
      {"text": "TL3", "goto": "TL3"},
      {"text": "Sidewinder", "goto": "Sidewinder"}
    ]
  },
  "TL3": {
    "text": "You consider your options. The Sidewinder would provide a straight, powerful shot, but it will need perfect control. The TL3, on the other hand, promised a more controlled flight, but with a higher risk of deviation if not thrown correctly.\n\nFinally, you make a decision. The TL3 seems like the best choice for this hole. Its ability to navigate the curves and glide through the fairway would be invaluable.\n\nTaking a stance on the tee pad, you hold the TL3 with a firm grip. The trees ahead seem to close in, but you feel good about your choice of disc. Focusing on the line, you take a deep breath, exhale slowly, and begin your throw. The TL3's flight path perfectly matches what you were hoping for. It weaves through the trees, following the curves of the fairway with ease. After a long, missed putt, you take an uneventful par.",
    "choices": [{"text": "Keep playing", "goto": "Keep playing"}]
  },
  "Sidewinder": {
    "text": "You choose the Sidewinder and step up to the tee pad. Your throw is nice, but looks like it might come up a little short. As the disc nears the basket, it glides gracefully to a stop, landing just inside the circle. A challenging but makeable birdie putt awaits. You walk briskly down the fairway, heart pounding with a mix of relief and excitement.\n\nReaching your disc, you take a moment to steady your nerves. The putt is about 30 feet, slightly uphill. Drawing on the confidence built over the previous holes, you focus, aim, and release the putter. You miss and feel yourself getting angry. You know you need to control your anger or the rest of the round will not go well.",
    "choices": [{"text": "Try not to be mad", "goto": "Try not to be mad"}]
  },
  "Head toward your disc": {
    "text": "As you walk toward your disc, a smile of accomplishment stretches across your face. Suddenly, out of nowhere, a sharp pain strikes your head. A stray disc, thrown by another player on an adjacent hole, had hit with brutal force. You stagger, falling to the ground as blood begins to pour from the wound. The world around blurred, the pain intense and disorienting. Fellow disc golfers rush to your side, calling for help, but the damage was severe.\n\nEmergency services arrive quickly, and you are transported to the nearest hospital. Doctors work tirelessly, but the injury is catastrophic. You slip in and out of consciousness, surrounded by the beeping machines and the worried faces of loved ones.\n\nDespite the efforts of medical staff, your injuries are too great. You spend a week in the hospital, fighting for life amidst waves of pain and fleeting moments of clarity. Friends and family visit, sharing stories and offering support, but the outcome seems inevitable.\n\nOne quiet evening, as the hospital lights flicker softly and the world outside continues on, your body succumbs to the injuries, and you pass away peacefully.\n\n THE END",
    "choices": []
  },
  "Finish your round": {
    "text": "You are having an incredible round. Each throw has been executed with precision, and as you approach the 17th hole, you feel an electric mix of excitement and confidence. The 17th is a challenging 250-foot par 3, with a narrow fairway flanked by trees and a slight dogleg to the left. You grab an Enigma, take a deep breath, focus, and let the disc fly. The Enigma soars through the air, gliding effortlessly down the fairway, curving slightly left as it approaches the basket.\n\nThe disc hits the chains dead center and drops into the basket with a satisfying clang. An ace! A group of players on another hole witness your shot, and erupt into cheers, high-fives all around. Your heart races with adrenaline and joy. It was a perfect throw, and the sense of accomplishment is immense.\n\nWith a huge smile, you approach the 18th and final hole. This last hole is a 375-foot par 3, featuring a water hazard along the left side and a basket perched on a gentle slope at the end of the fairway.\n\nFor your final drive, you choose the DD3, and step onto the tee pad. You take a few seconds to savor the moment, the cheers of the other players still ringing in your ears. The DD3 cuts through the air like a missile, gliding over the water hazard with ease. It maintains a straight, powerful flight, and as it nears the basket, it begins to descend. More people are watching this time, since the 18th hole is by the parking lot. The crowd holds their breath as the disc hit the chains with a resounding crash and settles into the basket.\n\nAnother ace! The crowd erupts into even louder cheers and applause. You can't believe it—two aces in a row to finish the round! It was the stuff of dreams, an unforgettable ending to an incredible day.\n\nTHE END",
    "choices": []
  },
  "Keep playing": {
    "text": "You approach the final hole of your round, feeling pretty neutral about the day. Every throw has been predictable—neither spectacular nor disastrous. The 18th hole, a 375-foot par 3, is no different. You select the S-Line DD3, and made your throw. It lands in the middle of the fairway, just like many of your other throws today.\n\nWalking up to your disc, you line up the approach shot, make a solid but unremarkable throw, and land close to the basket. A routine putt later, you tap in for par. As you walk back to the parking lot, you feel a mild sense of completion but nothing more. It had been an average round, a day that would blend into countless others, nothing to write home about.\n\nTHE END",
    "choices": []
  },
  "Try not to be mad": {
    "text": "You get your anger under control, make some great shots, and soon your demeanor lightens. You are having a great time when you approach the final hole. Hole 18, a challenging 375-foot par 3, features a beautiful yet daunting water hazard that runs along the left side of the fairway, ending just shy of the basket.\n\nYou throw your driver perfectly, arcing over the water and gliding toward the basket. However, a gust of wind catches the disc just before it lands, pushing it slightly left into the water.\n\nDetermined to finish the round strong, you walk over to the water's edge. The disc is visible just a few feet from the shore, resting on a submerged sandbar. You step into the shallow water, careful not to lose balance. As you reach out for the disc, a sudden, violent splash shatters the calm surface of the water. Before you can react, powerful jaws clamp around your leg. The pain was immediate and intense as the alligator's teeth sink in. With a terrifying, primal force, the alligator yanks you off balance, dragging you deeper into the water.\n\nA shout of horror escapes your lips, but it is cut short by the water closing overhead. Other disc golfers scream and run for help, but the alligator is relentless, it's powerful body twisting and turning, pulling you further into the murky depths. The world above becomes a blur of sunlight and water. The alligator's grip is unyielding, and within moments, the struggle subsides, the water growing still once more, as your disc floats aimlessly on the water.\n\nTHE END",
    "choices": []
  },
  "Move On": {
    "text": "Trying not to be too upset about the bogey, you move on to the next hole, a technical 350-foot par 3 that will need control rather than sheer power. The fairway is lined with dense trees, requiring a great shot to navigate through the tight gaps.\n\nYou pull the Titanium Undertaker from your bag. The Undertaker excels in delivering straight, controlled flights. It is ideal for threading narrow fairways and handling tricky shots. You also grab your ESP Athena, a slightly overstable disc, perfect for windy conditions.\n\nHolding both discs, you step up to the tee pad, feel the wind gusts, and plan the shot accordingly. The idea is to throw the Athena on a slight anhyzer angle, letting it fight the crosswind and glide toward the basket or to throw the Undertaker on a slight hyzer angle, allowing it to flip up to flat and glide straight down the fairway. Which disc do you choose?",
    "choices": [
      {"text": "Athena", "goto": "Athena"},
      {"text": "Undertaker", "goto": "Undertaker"}
    ]
  },
  "Athena": {
    "text": "The Athena performs beautifully, its overstable flight cuts through the crosswind with ease. It holds the anhyzer line for a moment before flexing back to a straight flight, gliding towards the hill where the basket awaits. As it nears the green, the Athena begins its predictable fade, landing safely near the base of the hill.\n\nWalking toward your disc, you feel the thrill of mastering a difficult shot. The Athena had handled the wind perfectly, setting up a manageable uphill putt. You grab your putter once more, and approach the basket, taking a moment to steady your nerves.\n\nThis uphill putt will require extra focus and power. You line up the shot, aim carefully, and release the putter with a firm flick. The disc flies straight and true, hitting the chains and dropping into the basket. Great birdie.",
    "choices": [{"text": "Continue your round", "goto": "Continue your round"}]
  },
  "Undertaker": {
    "text": "The Undertaker holds a steady line, weaving past the trees and maintaining control throughout its flight. As it approaches the basket, the disc began to fade, and lands perfectly in the fairway just short of the basket.\n\nWalking towards your disc, you are happy the Undertaker had navigated the challenging fairway flawlessly, setting up an easy putt. You grab your putter and after a quick tap-in, you secure the birdie, a satisfying result on a difficult hole.\n\nNow that you've made up for your bogey, you might be able to enjoy the rest of your round. You hope it continues to go well for you.",
    "choices": [{"text": "Continue playing", "goto": "Continue playing"}]
  },
  "Continue your round": {
    "text": "A few holes later, you approach a challenging 420-foot par 4 with a tight, wooded fairway that opens up near the basket. It will require a disc with both distance and control, and you think the ESP Anax might be the perfect choice for the job. You also consider your Titanium Raptor, a disc known for its overstable flight and wind-fighting capabilities, as this hole will require a disc that can cut through the gusts with ease.\n\nYou grab both discs, step up to the tee pad, and take a moment to assess the wind. The plan is keep the disc on a straight path and make your approach as easy as possible. Which disc do you choose?",
    "choices": [
      {"text": "Raptor", "goto": "Raptor"},
      {"text": "Anax", "goto": "Anax"}
    ]
  },
  "Raptor": {
    "text": "The Raptor does its job and stays on course despite the strong headwind. It holds a steady line, slicing through the gusts and maintaining control. As it flies through the air, the disc begins to fade, landing safely in the middle of the fairway.\n\nWalking toward your disc, you feel great about your throw. The Raptor had handled the headwind perfectly, setting up an easy approach to the basket. You grab your putter, line up the shot and deliver a perfect throw, landing the disc within a few feet of the basket.\n\nA quick tap-in secures the birdie, an amazing result given the tough conditions. You feel like the rest of your round should go well, as this is as tough as the course gets. Nothing can stop you now.",
    "choices": [{"text": "Finish Strong", "goto": "Finish Strong"}]
  },
  "Anax": {
    "text": "The Anax flies incredibly, its stability keeping it on a straight path through the narrow fairway. It navigates the trees with ease, holding a steady line. As it approaches the opening near the basket, the disc begins to fade, landing perfectly in the clearing.\n\nThe Anax had performed exactly as planned, setting up a manageable second shot. Choosing your putter for the approach, you aim to land the disc near the basket for an easy putt.\n\nYour shot lands softly within putting distance. You approach the basket and tap in for a comfortable birdie. You are excited that the Anax had delivered a flawless drive. The rest of the round should be great.",
    "choices": [{"text": "Finish the round", "goto": "Finish the round"}]
  },
  "Finish Strong": {
    "text": "You're having an incredible round, and are excited about finishing well. The last hole is a picturesque 350-foot par 3, with a downhill slope and a clear view of the basket nestled between a cluster of trees. Your drive flies straight and true, navigating the fairway and landing within putting distance of the basket.\n\nYou walk toward your disc, a smile of contentment stretches across your face. You decide to take a moment to enjoy the success of the round and lean against a nearby tree to rest. Suddenly, you feel a sharp, unexpected pain in your arm.\n\nLooking down, you see a small, brightly colored snake slither away into the underbrush. Almost immediately, the area around the bite begins to swell and throb. Panic sets in as you realize the snake was likely venomous. Other disc golfers notice your distress and rush over to help. One of the players quickly identifies the snake as a coral snake, known for its potent venom. They call for emergency services while trying to keep you calm and still. Despite the quick response, the venom spreads rapidly, causing intense pain and paralysis in your arm.\n\nAt the hospital, doctors work to treat the bite, administering antivenom and pain relief. The medical team manages to save your life, but the damage to your arm is severe. The venom has caused extensive nerve damage, resulting in permanent paralysis of your arm.\n\nThe weeks that follow are filled with rehabilitation and adjustment. Once a passionate and skilled disc golfer, you face the harsh reality that playing disc golf again is no longer possible.\n\nTHE END",
    "choices": []
  },
  "Finish the round": {
    "text": "You are having a fantastic round. Each throw seems to land exactly where you intend, and the satisfaction of a well-played game fills you with excitement. You approach the 18th and final hole, a 375-foot par 3, featuring a scenic fairway with a slight dogleg left and a basket nestled near a small grove of trees.\n\nYou take out your S-Line DD3 and throw the disc gracefully down the fairway, curving it perfectly around the dogleg and landing just shy of the basket.\n\nAs you're walking down the fairway, something catches your eye. A small bundle of cash is lying in the middle of the fairway. You bend down to inspect it and are shocked to find that it is a stack of hundred-dollar bills, totaling $1,000.\n\nYour first instinct is excitement, but it is quickly tempered by a sense of responsibility. You don't want anyone to think you are stealing, so you look around, but the course is empty. There is no one in sight, and no immediate sign of who might have lost the money.\n\nDeciding to do the right thing, you pick up the money and head back to the clubhouse. You inform the course manager about the find and explain your intention to wait for the owner to claim it. The manager appreciates your honesty and agrees to hold the money at the clubhouse. He thanks you for your integrity and assures you that if no one claims the money within a week, it will be returned to you as the finder.\n\nFinally, a week later, you receive a call from the course manager. No one had claimed the $1,000, and it was now rightfully yours. You drive to the course to collect the money and on the way home with it safely in your pocket, you reflect on the day. You had not only been tested on the disc golf course, but you had also been tested in your integrity, and you passed both with flying colors. The $1,000 was a welcome surprise, but it was the sense of doing the right thing that truly made the experience rewarding.\n\nTHE END",
    "choices": []
  },
  "Continue playing": {
    "text": "You reach a scenic 400-foot par 3, featuring a curved fairway with a clear, open field leading to a basket nestled among a few tall pines. It is a hole that will require your best. The Jawbreaker Thrasher, with its high-speed flight and reliable turn, might be great for this shot. The Avenger SS, crafted from ESP plastic, feels good in your hands. It's understable flight makes it ideal for turnovers and hyzer flips, especially when navigating open fairways.\n\nThe plan is to throw the Avenger SS on a slight hyzer angle, allowing it to flip up to flat, turn right, and glide toward the basket, or to throw the Thrasher on a slight anhyzer angle, so it flexes back to a straight flight and maximizes distance.\n\nStepping up the tee pad, you take a deep breath and hope you make the right decision. Which disc do you choose?",
    "choices": [
      {"text": "Avenger SS", "goto": "Avenger SS"},
      {"text": "Thrasher", "goto": "Thrasher"}
    ]
  },
  "Avenger SS": {
    "text": "The Avenger SS soars through the air, its understable nature allowing it to flip up to flat as planned. It begins a controlled turn to the right, gracefully navigating the curve of the fairway. The disc's glide is remarkable.\n\nAs it approaches the cluster of tall pine trees, the Avenger SS begins to fade, settling down softly in a perfect spot on the fairway. The throw had covered the distance nicely, setting up a manageable appraoch shot for a birdie opportunity.\n\nThe Avenger SS had performed well. You walk down the fairway and upon reaching your disc, you take a moment to appreciate the nature all around you and the successful throw. Nothing can go wrong now.",
    "choices": [{"text": "Try to keep playing well", "goto": "Try to keep playing well"}]
  },
  "Thrasher": {
    "text": "The Thrasher's high-speed turn allows it to navigate the wide-open fairway with ease. It flexes back to a straight flight, covering a significant amount of distance. As it nears the basket, the disc begins to fade, landing perfectly in the fairway.\n\nWalking toward your disc, you feel a rush of exhilaration. The Thrasher had delivered an incredible drive, setting up a manageable second shot. You aim to land the disc near the basket for an easy putt. However, the wind picks up as you throw your approach shot, and you terribly misjudge the power. After a mediocre 3rd shot and a missed 25ft putt, you take a bogey. Things can't get any worse.",
    "choices": [{"text": "Try to do better", "goto": "Try to do better"}]
  },
  "Try to keep playing well": {
    "text": "The day has been calm, and so has your game. Each hole has been consistent, with pars dominating the scorecard. The 18th hole is a familiar challenge, and you approach it with the same methodical precision you've had all day. You throw your S-Line DD3, watch it land in a predictable spot, and make your way down the fairway.\n\nYour second shot places the disc near the basket, and you complete the hole with an easy putt. Packing up your gear, you reflect on the round. It had been solid and consistent, but there were no highlights, no memorable moments. It was a round that, while not bad, was entirely forgettable.\n\nTHE END",
    "choices": []
  },
  "Try to do better": {
    "text": "You approach the 18th hole, determined to not let the previous holes ruin the end of the round for you. This last hole is a challenging 375-foot par 3, featuring a beautiful yet daunting water hazard running along the left side of the fairway, ending just shy of the basket.\n\nYou choose your DD3 and release the disc with a powerful throw. The DD3 soars through the air, but a sudden gust of wind catches the disc, pushing it left. It arcs beautifully but, to your dismay, it lands in the water hazard.\n\nDetermined not to end the round on a low note, you decide to throw another disc. Pulling out your Enigma, you take a deep breath and aim carefully. This time, the disc stays straight but falls short, splashing into the water just shy of the basket. Frustration mingles with determination as you watch it sink.\n\nRefusing to let the day end with two discs lost, you grab another from your bag—this time, the Instinct. With a mix of hope and focus, you release the disc, only to see it fade unexpectedly and land in the water. The frustration mounts, but so does your resolve.\n\nOne by one, you try each disc. The Mentor, the Beast, the Katana, and even your trusty putter—all meet the same watery fate. Each throw feels desperate and none find their mark.\n\nFinally, you hold your last disc—the Thrasher. This disc is now your last hope. It flies beautifully, gliding straight, only to skip off a rock, sending it tumbling into the water with a final, deflating splash. You stand there, breathless and staring at the rippling water, the realization setting in. All of your discs are gone.\n\nTHE END",
    "choices": []
  },
  "On to the next hole": {
    "text": "The next hole is a beautiful 320-foot par 3, with a downhill slope and a narrow fairway lined with tall pines. The basket is positioned slightly to the right. 2 discs come to mind for this shot, the S-Line Mentor, a distance driver with reliable stability and the C-Line Essence, a fairway driver that excels in controlled, accurate shots.\n\nYou plan to throw the Mentor on a slight hyzer angle, allowing it to flip up to flat and glide down the fairway, or throw the Essence on a slight anhyzer angle, allowing it to turn gently to the right and glide towards the basket. Which disc do you choose?",
    "choices": [
      {"text": "Essence", "goto": "Essence"},
      {"text": "Mentor", "goto": "Mentor"}
    ]
  },
  "Essence": {
    "text": "The Essence flies with impressive glide, its slight anhyzer angle allowing it to turn slightly to the right. The disc navigates the narrow fairway with ease, maintaining a steady, controlled flight. As it approaches the basket, the Essence begins to fade a little, landing perfectly within putting distance.\n\nThe Essence had performed flawlessly, executing the shot as planned. You grab your putter, and line up the next shot, keeping your eyes on the chains. The putt is straightforward, and you feel confident in the outcome. You release your putter with a quick, efficient stroke.\n\nThe disc holds its line, hitting the chains solidly, but the disc bounces back out and drops next to the basket. It's a tough miss, and thanks to a great drive combined with a bad break, you'll walk away with a par.",
    "choices": [{"text": "Play more disc golf", "goto": "Play more disc golf"}]
  },
  "Mentor": {
    "text": "The Mentor's slight hyzer angle flips up to flat as planned. The disc flies effortlessly, maintaining a straight flight before beginning a slight fade to the left. As it approaches the green, the Mentor continues to glide, avoiding the scattered trees and landing perfectly in the circle.\n\nWalking toward your disc, you feel a surge of happiness. The Mentor had done well, executing the planned shot perfectly. All thats left now is to make a fairly easy putt.\n\nHowever, you lose your concentration for a moment, and miss a putt that you make 95% of the time. This could ruin your round. Trying not to be mad is easier said than done, and you find yourself dwelling on this hole. It wasn't a bogey, but it sure felt like one.",
    "choices": [{"text": "Try to move on", "goto": "Try to move on"}]
  },
  "Play more disc golf": {
    "text": "The next few holes go well for you. There wasn't any birdies, but you have played great, and you're happy with your game so far.\n\nLater in the round, you reach a more forgiving 375-foot par 4. This hole offers a mix of open space and strategic obstacles. The fairway itself is a broad expanse of short grass, and it slopes downhill. About 250 feet from the tee, the fairway narrows at a line of mature oak trees that span across the fairway from left to right, marking the transition from the open meadow to a more wooded area.\n\nThe key challenge of this hole is navigating past these trees. There are a few gaps between them, but you must choose your line carefully to avoid being blocked or knocked off course. The basket is placed just beyond these trees, on the edge of a small grove. You pull out 2 of your drivers, the Enigma and the DD3. Which disc do you choose?",
    "choices": [
      {"text": "Enigma", "goto": "Enigma"},
      {"text": "DD3", "goto": "DD3"}
    ]
  },
  "Enigma": {
    "text": "You decide to throw the Neo Enigma, a distance driver with reliable stability. The Enigma feels nice in your hand, the premium plastic looks good too. This disc is perfect for long drives, making it ideal for this open fairway.\n\nYou step up to the tee pad, and take a moment to think about your shot. You release the Enigma on a slight hyzer angle and the disc flies forward, flipping up to flat as it gains distance. It stays on a straight path, gliding down the fairway.\n\nAs it approaches the basket, the Enigma begins to fade, landing perfectly in the fairway with a clear line to the basket. For your approach, you hope to land the disc as near to the basket as possible. Your disc flies straight and lands well within the circle. You approach the basket and tap in for a comfortable birdie.",
    "choices": [{"text": "Keep going", "goto": "Keep going"}]
  },
  "DD3": {
    "text": "The S-Line DD3 will take full advantage of the slope, and maximize distance while maintaining control, so you step up to the tee pad and throw it on a slight hyzer angle. The disc flies well, flipping up to flat as it gains distance. The DD3 stays on a straight path, gliding down the slope as expected.\n\nThe DD3 fades out at the end of it's flight, landing in the fairway with a clear line to the basket. Walking toward your disc, you feel exhilarated. The DD3 has delivered an impressive drive, covering a significant amount of distance. On your approach, you aim to land the disc near the basket, but it doesn't work out as expected. You are still about 30ft away, and after another missed putt, you tap in a par. You hope to play better.",
    "choices": [{"text": "Try to play better", "goto": "Try to play better"}]
  },
  "Try to play better": {
    "text": "As you approach the final hole, your scorecard reflects a day of mediocrity. A couple birdies, a couple bogeys, and a string of pars that mark an entirely average round. The 18th hole is a familiar sight, and you prepare to throw your S-Line DD3 again. The disc flies as expected, landing safely on the fairway.\n\nYour approach shot is equally uneventful, and a routine putt completes the hole. Walking off the course, you feel neither the high of a great round nor the frustration of a poor one. Other than the one nice putt on hole 1, it was just another day of disc golf, one that will fade into the background of your many rounds played.\n\nTHE END",
    "choices": []
  },
  "Keep going": {
    "text": "You've had an exceptional round so far, and by the time you reach the 18th and final hole, you feel excited about finishing your round strong. The last hole is a challenging 300-foot par 3, featuring a fairway bordered by dense woods on both sides. Stepping onto the tee pad, you select the MD3. It flies beautifully, gliding down the fairway, but as it approaches the basket, it catches a gust of wind and veers left, disappearing into the woods.\n\nYou walk toward the tree line, determined to find your disc and complete the round. The dense underbrush and tall trees create a shadowy canopy, making it difficult to see more than a few feet ahead. As you venture deeper into the woods, you spot your disc lodged against the base of a large tree.\n\nRelieved, you approach the disc, but a rustling sound nearby catches your attention. Turning your head, you freeze. Emerging from the shadows was a massive black bear, its eyes locking onto yours with an intensity that sends a chill down your spine. The bear, initially curious, begins to show signs of aggression, its ears flattening and a low growl emanates from its throat.\n\nYou know you need to stay calm, but the proximity of the bear and the isolation of the woods make escape seem impossible. You slowly start to back away, trying to avoid sudden movements that might provoke the animal. However, the bear advances, its growls growing louder and more menacing. You turn to run, but the bear charges with incredible speed. In moments, the bear is upon you, knocking you to the ground. You scream for help, but your cries are swallowed by the dense forest. The bear's powerful jaws and claws leave no chance for escape or survival.\n\nThe forest, usually a place of peace and solitude for you, has turned into a scene of horror. The bear mauls you mercilessly, and within minutes, the woods fall silent again.\n\nTHE END",
    "choices": []
  },
  "Try to move on": {
    "text": "The next hole is a technical and challenging par 3 that spans 280 feet, nestled deep within a heavily wooded area. This hole immediately tests a player's patience and control.\n\nThe tee pad is embedded in a natural clearing, surrounded by towering pine trees. As you stand on the tee, you can see the fairway stretch out in front of you, a narrow path flanked by thick underbrush and tall trees. The fairway is only about 20 feet wide at its narrowest point, creating a tunnel effect that demands an accurate, straight throw to avoid the thick rough on either side. The basket is positioned at the end of the fairway, slightly elevated on a small mound and surrounded by a few large rocks and scattered bushes.\n\nYou decide a fairway driver will be the right disc for this hole, and grab 2 from your bag. You look at your Instinct and the more overstable Splice. Which disc do you choose?",
    "choices": [
      {"text": "Instinct", "goto": "Instinct"},
      {"text": "Splice", "goto": "Splice"}
    ]
  },
  "Instinct": {
    "text": "The C-Line Instinct feels good in your hand, the premium plastic providing excellent grip. The disc is ideal for controlled, accurate throws, making it perfect for this tight fairway. You hope to avoid the trees and land close to the basket.\n\nOnce you're on the tee pad, and ready to throw, you release the Instinct on a flat angle. The disc flies straight and holds its line. It glides down the fairway, narrowly missing the trees on either side.\n\nAs the disc approaches the basket, it begins to fade slightly, landing perfectly within the circle. You grab your putter and get ready for your birdie attempt. Lining up the putt, you take a deep breath and release the putter. The disc flies straight into the chains, securing a satisfying birdie.",
    "choices": [{"text": "Try to get more birdies", "goto": "Try to get more birdies"}]
  },
  "Splice": {
    "text": "You decide the Neo Splice, an overstable fairway driver, is the ideal choice. This disc is great at navigating tight, wooded fairways, but you will still need to have a great shot if you want to get close enough to the basket for another shot at a birdie.\n\nYou step onto the tee pad and think a little longer about your shot than you normally would. When you're ready, you throw the Splice on a slight anhyzer angle. The disc flies forward, and seems to be navigating the fairway with ease.\n\nAs the disc approaches the green, it barely avoids the trees, and glides towards the basket. The Splice's stability keeps it on a precise line, landing perfectly within the circle. This should be an easy birdie for you.",
    "choices": [{"text": "Try to make your birdie", "goto": "Try to make your birdie"}]
  },
  "Try to get more birdies": {
    "text": "You are having the round of a lifetime. Every throw is precise, every putt finds its mark, and the satisfaction of a well-played game is building with each hole. As you approach the 17th hole, there is a palpable sense of excitement. This was shaping up to be the best round you have ever played.\n\nThe 17th hole is a short 250-foot par 3, and eveything seems easy to you today. You grab your Neo Enigma, get ready to throw, and fire it off the tee. It flies straight, threading the needle between the trees and landing softly just feet from the basket. A quick putt secures a birdie.\n\nWith adrenaline pumping, you approach the 18th hole. This last hole is a 375-foot par 3, with a water hazard on the left and a basket placed on a slight slope at the end of the fairway. The pressure is on, but you feel calm.\n\nChoosing your DD3, you step onto the tee pad,imagine the flight path, and unleash a powerful throw. The DD3 soars through the air, cutting through the breeze and maintaining a perfect trajectory. It glides over the water hazard and lands gracefully on the fairway, rolling up to within putting distance of the basket.\n\nTaking a moment to steady yourself, you line up the final putt. It finds the center of the chains with a satisfying clang. The round is complete, and you've not only finished strong but also achieved the best score of your life.\n\nYour final score sets a new course record, breaking the previous mark by two strokes. Driving home, you can't stop smiling. The day had been magical, reaffirming your love for the game. It is the perfect ending to an amazing round.\n\nTHE END",
    "choices": []
  },
  "Try to make your birdie": {
    "text": "It was not an easy birdie. It wasn't even a par, and after a terrible putt goes awry, it turns into a bogey. And that was how the rest of the round went, terrible shot after terrible shot. By the time you reach the 18th and final hole, frustration has taken hold. Standing there, looking at the scorecard filled with bogeys, double bogeys, and worse, you feel a wave of despair. It was the worst round of disc golf you've ever played.\n\nWalking off the course, you feel the heavy weight of doubt. The joy and confidence of past rounds seem like a distant memory, replaced by frustration and disappointment, the idea of giving up taking root.\n\nBack at the car, you sit and stare at the empty course as the sun dips below the horizon. The thought of never playing again seems reasonable.\n\nTHE END",
    "choices": []
  }
};

// Export for use in story engine
if (typeof module !== 'undefined' && module.exports) {
  module.exports = STORY_DATA;
}
